TestPaperCreator.UI/Controllers/Membership/MembershipAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using TestPaperCreator.MODEL.Membership;
using System.Web.SessionState;
using System.Web;
using TestPaperCreator.BLL;

namespace TestPaperCreator.Controllers.Membership
{
    public class MembershipAPIController : ApiController
    {
        [Route("api/MembershipAPI/Register")]
        [HttpPost]
        public TestPaperCreator.MODEL.Utility.Result Register(User user)
        {
            TestPaperCreator.MODEL.Utility.Result result = BLL.Membership.Membership.Regist(user);
            return result;
        }
        [HttpPost]
        public bool Login([FromBody]User user)
        {
            bool result = TestPaperCreator.BLL.Membership.Membership.Login(user);
            if (result == true)
            {
                var rememberme = user.rememberme;
                HttpSessionState session = HttpContext.Current.Session;
                session.Add("user", BLL.Utility.Utility.Serialize<User>(user));
                //session["user"] = TestPaperCreator.BLL.Utility.Utility.Serialize<User>(user);
                if (user.rememberme == 1)
                {
                    HttpCookie cookie = new HttpCookie("UserInfo");
                    cookie.Value = TestPaperCreator.BLL.Utility.Utility.Serialize<User>(user);
                    cookie.Expires = DateTime.Now.AddDays(666);
                    HttpContext.Current.Response.Cookies.Add(cookie);
                }
            }
            return result;
        }
    }
}

TestPaperCreator.UI/Controllers/Membership/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestPaperCreator.Controllers.Membership
{
    public class MembershipController : Controller
    {
        // GET: Membership
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session.Remove("user");
            Response.Cookies["UserInfo"].Expires = DateTime.Now.AddDays(-1);
            Response.Redirect("/Home/Index");
            return View();
        }
        // GET: Membership/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Membership/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Membership/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Membership/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Membership/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Membership/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Membership/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TestPaperCreator.UI/Views/Membership/login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <title>登录</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <style type="text/css">
        body {
            background-image: url(/images/background.jpg);
        }

        #container {
            width: 300px;
            margin: 100px auto;
        }
    </style>
</head>
<body>
    <div id="container">
        <br />
        <br />
        <br />
        <br />
        <img class="img-responsive" src="~/images/logo.png" />
        <br />
        <br />
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                <input class="form-control" id="username" placeholder="admin" onfocus="init()" />
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                <input class="form-control" id="password" type="password" placeholder="admin" onfocus="init()" />
            </div>
        </div>
        <div class="alert alert-danger" id="alert" style="display:none" role="alert"></div>
        <div class="checkbox">
            <label style="color:white"><input id="rememberme" type="checkbox" />请记住我</label>
        </div>
        <label class="label"><a style="cursor:not-allowed" class="pull-left" @*href="@Url.Action("Reset", "Membership")"*@>忘记密码？</a></label>
        @*<label class="label"><a class="pull-right" href="@Url.Action("Regist", "Membership")">注册新用户</a></label>*@
        <br />
        <br />
        <input class="form-control btn btn-success" style="display:inline-block" type="submit" id="submit" value="登录" onclick="login()" />
    </div>
    <div id="beian" style="text-align:center"><a style="color:white" target="_blank" href="http://www.miitbeian.gov.cn/">蜀ICP备15026501号-1</a></div>
</body>
</html>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/md5.js"></script>
<script src="~/Scripts/Membership/Login.js"></script>